spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigflag?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.jackluan.bigflag.domain.*.component.dataobject
  mapper-locations: classpath:mapper/*.xml

#引入日志配置文件
logging:
  config: classpath:log4j2.yml